### ISSUE TITLE
fail to open example files

### ISSUE THREAD

**Issue by iyhaoo** [EichlerLab/pacbio_variant_caller#57]
I have already installed this program but when I ran `smrtsv.py index reference/sacCer3.fasta` as the tutorial, it always outputs
```
Traceback (most recent call last):
  File "/public/users/yuanhao/SMS/SMRT-SV/pacbio_variant_caller/bin/smrtsv.py", line 554, in <module>
    return_code = args.func(args)
  File "/public/users/yuanhao/SMS/SMRT-SV/pacbio_variant_caller/bin/smrtsv.py", line 140, in index
    "reference=%s" % args.reference
  File "/public/users/yuanhao/SMS/SMRT-SV/pacbio_variant_caller/bin/smrtsv.py", line 133, in _run_snake_target
    return _run_cmd(prefix)
  File "/public/users/yuanhao/SMS/SMRT-SV/pacbio_variant_caller/bin/smrtsv.py", line 79, in _run_cmd
    p = subprocess.Popen(args, env=PROCESS_ENV)
  File "/usr/lib64/python2.6/subprocess.py", line 639, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1228, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
But when I inputed `cat reference/sacCer3.fasta`, it runs.

**Comment by paudano** [comment]
Closing. This project has been replaced with SMRT-SV v2 (https://github.com/EichlerLab/smrtsv2)
